### ISSUE TITLE
Bug in sequential mapping

### ISSUE THREAD

**Issue by nephantes** [UMMS-Biocore/dolphinnext#116]
It skips custom sequence set. Custom sequence set is not working. 
When I don't add any other common RNA's for loop is like below;

     for rna_set in 

When I add rRNA,GFP,miRNA for loop is below;

     for rna_set in rRNA  miRNA

But this part is right.

    prev="reads"
    IFS=',' read -r -a paramsListAr <<< "-N 1,-N 1,-N 1" #create comma separated array 
    IFS=',' read -r -a filtersListAr <<< "Yes,Yes,Yes"
    IFS=',' read -r -a indexesListAr <<< "/share/data/umw_biocore/genome_data/human/hg19/commondb/rRNA/rRNA,/project/umw_robert_kotin/data/gfp/gfp,/share/data/umw_biocore/genome_data/human/hg19/commondb/miRNA/miRNA"

So, it doesn't add name_of_the_index_file to the list;

**Comment by onuryukselen** [comment]
Bug fixed in sequential mapping. When description of the mapping is not entered then name_of_the_index_file will be used as a title of the mapping in the for loop.
