### ISSUE TITLE
Log Timeline display unreadable and/or wrong

### ISSUE THREAD

**Issue by lawrencelifshitz** [UMMS-Biocore/dolphinnext#162]
When looking at the timeline in the Log file from a pipeline with lots of processes, it seems like
all the process timeline bars are squished to the far right.  Also the x-axis labels (ie, the time)
start from 0 and go to 20. then start again at 0 and go to 3.  So I am guessing that the process
bars are all using just the last 3 values along the x-axis.
This can be seen in ChIP Run1 on the GHPCC cluster.

I would expect to see something like
https://www.nextflow.io/docs/latest/tracing.html#timeline-report

Maybe if there is a log time the parent nextflow process waits in the queue 
before it runs, that eats up
a lot of time and then all results are squished to the right?  But why would the x-axis time
labels start over?  If this is the reason, would there be some way to exclude the initial
waiting time from the output timeline?

see screen shots:

![XaxisLabels](https://user-images.githubusercontent.com/53879135/63047049-9debd000-bea1-11e9-8d6b-3385c4f4fba9.png)
![TheFirstProcesses](https://user-images.githubusercontent.com/53879135/63047050-9debd000-bea1-11e9-84a6-8aed001e208e.png)

I have tried this with both Chrome and Firefox on Fedora Core 25.  I have also clicked on
the "web link" button to see it larger. That does not fix the problem.

**Comment by onuryukselen** [comment]
Nextflow keeps the date of the first run attempt. When user start a new run with 'resume' option, it still shows the initial date as start point. That's why you see this empty time period.
