### ISSUE TITLE
Run Status shows a shared run, clicking on it shows nothing

### ISSUE THREAD

**Issue by lawrencelifshitz** [UMMS-Biocore/dolphinnext#165]
I click on Run Status. At the top of the list I see ID 1578 ChIP Run1-copy completed
by rw54w at 15:47.  If I click on the run name, or go to Options>view run
I get sent to a blank Biocore Run Generation page (ie, no info is filled in the fields).
I would have expected to see the Run name, run settings, etc.

![NoRunInfo](https://user-images.githubusercontent.com/53879135/63131976-943f9680-bf8d-11e9-9412-9c9d368c3e38.png)

I am not sure why this is happening and how to reproduce the error.
I have been able to see results from other runs by rw54w.
I did NOT see this run listed in Run Status before it completed - I'm not sure
if that is related to this problem or not.

Using FC25 and the Chrome browser.

**Comment by onuryukselen** [comment]
Permission of this revision of the pipeline is changed by the user rw45w. So it's not shared by him anymore. You might reach to him about this problem.
