### ISSUE TITLE
Running DolphinNext locally

### ISSUE THREAD

**Issue by prihoda** [UMMS-Biocore/dolphinnext#181]
Hi, is there any documentation on running your own instance of DolphinNext? I would like to try running it locally.

To that end, are you considering providing a Docker image for DolphinNext? It should be straightforward, you would just need to define all dependencies and the server execution command. Then, anyone could simply run something like `docker run UMMS-Biocore/dolphinnext` to execute their own server.

**Comment by onuryukselen** [comment]
We have a tutorial, please check the following link:
https://github.com/UMMS-Biocore/dolphinnext-tutorial
You can easily pull the docker image and create pipelines.

**Comment by prihoda** [comment]
Great, thanks! I think you should add that to the main DolphinNext readme or the documentation site. Or if it's already there, please make it more visible since I cannot seem to find it 😄
