### ISSUE TITLE
Sending emails problem in docker image

### ISSUE THREAD

**Issue by nephantes** [UMMS-Biocore/dolphinnext#210]
When email params are not set in docker image in dolphinnext-studio, it doesn't send the emails.
https://github.com/UMMS-Biocore/dolphinnext-studio

**Comment by nephantes** [comment]
Make sure to change the email addressis in /var/www/html/dolphinnext/.sec file.

EMAIL_SENDER=support@your_domain.com
EMAIL_ADMIN=admin@your_domain.com

Check you junk folder after you try, they might go there.

**Comment by VangelisTheodorakis** [comment]
The .sec file was not present in that path, so I filled it with a plain gmail, for testing purposes but still does not work. Should I set something else as well like password, port smtp server etc?

**Comment by nephantes** [comment]
It should be under
/var/www/html/dolphinnext/config/.sec
Let me know if you can find it.

**Comment by VangelisTheodorakis** [comment]
Do I have to set some other fields also in order for a regular Gmail to work?

**Comment by nephantes** [comment]
It looks like you need to define something specific to gmail.
https://linuxconfig.org/configuring-gmail-as-sendmail-email-relay
However, I couldn't be successful myself due to the two factor authentication in gmail.

**Comment by VangelisTheodorakis** [comment]
Yeah I myself reached the point where I would get some notifications from Gmail for some shady activity on behalf of my account but I never received any mails. Have you also manage to successfully send emails running your own email server with sendmail and if yes do you have a tutorial for that?

**Comment by nephantes** [comment]
There is nothing else required to send emails successfully. Just setting EMAIL_SENDER, EMAIL_ADMIN in config/.sec file should be sufficient to get it worked.
