### ISSUE TITLE
A little puzzle

### ISSUE THREAD

**Issue by fitzgeraldZoeky** [UMMS-Biocore/dolphinnext#220]
Hi, I am a student form China.
   I've seen your paper and that is great, so I want to learn some knowleadge of JavaScript from your project, but I couldn't find a file like 'main.js'. Could you please give a hand ?
   Thank you !

**Comment by nephantes** [comment]
The javascript code might not always be in a main.js file in different projects. When the browser loads the page, the browser has a built-in interpreter that reads the JavaScript code it finds in the page and runs it.

**Comment by fitzgeraldZoeky** [comment]
Oops,&nbsp; I just start to learn Js,&nbsp; now I get it. I am trying to figure out relationship between these files. Thanks a lot



---Original---
