### ISSUE TITLE
About docker url only can use localhost.

### ISSUE THREAD

**Issue by jackycsie** [UMMS-Biocore/dolphinnext#230]
Hi team,

I try many time.
No matter I use Dockerfile build docker or pull docker.
https://github.com/UMMS-Biocore/dolphinnext-docker

Dolphinext can not login to other LAN PC website.
Because Dolphinext only can use localhost.

Could you tell me. How to use other LAN PC browser connect server Dolphinext ?

BR,
Jacky

**Comment by nephantes** [comment]
How do you define the host in the profile?
Please check the link below;
https://dolphinnext.readthedocs.io/en/latest/dolphinNext/quick.html#creating-profile

**Comment by jackycsie** [comment]
@nephantes  Thank you your suggest.
When I edit /export/dolphinnext/config/.sec file.
dolphinnext can connect in LAN PC.
