### ISSUE TITLE
RNASeq pipeline adapter trimmer unpaired R2 missing

### ISSUE THREAD

**Issue by lawrencelifshitz** [UMMS-Biocore/dolphinnext#261]
**Describe the bug**
If I look at the unpaired/  folder after an a bulk RNASeq pipeline run which 
used the trimmomatic adapter trimming (eg,/project/umw_michael_czech/WAT_NEW_lml/run2608/work/5d/bdb7216d9cf258b0ccdc39db7755c7/unpaired ) the R2 file is missing.
Looking at the command line used, it seems that the same file was specified
for the output of both R1 and R2 unpaired data.

**To Reproduce**
I assume any run of the RNASeq pipeline which uses the adapter trimming
would have the same problem but I have not checked.

**Expected behavior**
I would think there would be both an R1 and R2 file in the unread/ folder.

**Comment by onuryukselen** [comment]
Hi Larry, thanks for pointing out this issue. It's fixed for adapter removal process.
