### ISSUE TITLE
Add Output ENV Qualifier

### ISSUE THREAD

**Issue by thakk** [UMMS-Biocore/dolphinnext#275]
Hello,

Would it be possible to add ENV output qualifiers ( see https://www.nextflow.io/docs/latest/process.html#output-env ) ? Feature is highly useful when creating complex value inputs in preceding process.

Thank You for Your Consideration.

**Comment by onuryukselen** [comment]
Hi, ENV qualifier added in version 1.2.4 (#276). You can run the following command to update your local mirror to latest version. 
```python scripts/updateDN.py```

**Comment by thakk** [comment]
Thank You, works like a charm!

Also i had to switch more recent version from .sec , but that's trivial.
