### ISSUE TITLE
Missing Project Files upload button

### ISSUE THREAD

**Issue by schorlton** [UMMS-Biocore/dolphinnext#60]
**Describe the bug**
Project Files section is missing an upload files button as described in the documentation (see screenshot below).

**To Reproduce**
1. Build and run docker version from latest commit.
2. Install php7.2-ldap in the container
3. Register new user, activate and login as new user
4. Create new project
5. Scroll in the project to "Project Files" section

**Expected behavior**
Upload files button present to upload new files.

**Screenshots**
![image](https://user-images.githubusercontent.com/10245822/53276799-9ea36680-36b5-11e9-98a4-15ea76b218dd.png)

**Comment by onuryukselen** [comment]
We moved that feature into run page, where you can easily enter your files paths or values for the defined inputs. I will update documentation accordingly.
