### ISSUE TITLE
License is contradictory with README

### ISSUE THREAD

**Issue by zeehio** [UMMS-Biocore/dolphinnext#88]
Either the software is released under the GNU GPL license, as stated on the `LICENSE` file and therefore, as it is stated in your LICENSE file, it is free to use for any purpose and can be redistributed for a fee; or it is only available for `nonprofit academic use` as stated in the README and therefore it is not free software (may be "free" as in "free beer", but not as in "freedom").

Note that if DolphinNext is only available for `nonprofit academic use` then it will most likely be excluded from being packaged in all free software linux distributions (Debian, Fedora, Ubuntu) because yes, free software allows us to sell Debian CDs if we want to.

I'm a non-profit academic user, so it does not directly affect me, but you may be interested in learning about free software vs "academic only" licenses.

**Comment by nephantes** [comment]
This license is only for academic users. We sign different agreements with non-academic users. For academic and non-profit organizations, they can distribute, copy but they cannot change the code. With this license we want to protect DolphinNext users served by other non-profit and academic organizations that these users should have access to the source of DolphinNext and this source cannot be changed without our knowledge. If it is an academic organization for profit, or non-academic organizations work for profit, we have another license for those organizations.

**Comment by zeehio** [comment]
The way dual license usually works is different as you are doing, and your way may have unintended interpretations. I guess licensing may be boring, but I hope to be able to help. I am not a lawyer (I am a not-for-profit academic right now), so consider getting professional advice if you want to.

### How dual licensing (GPL+alternative) usually works (and why)

- One of the requirements for software to be considered free software is that it allows the user to use the program for any purpose. "Not-for-profit only" software can't be considered free software. See https://opensource.org/osd-annotated or https://www.gnu.org/philosophy/free-sw.en.html

- On the other hand, most businesses base their business model on privative software, by selling non-redistributable, single user licenses.

The key to dual licensing (as you are thinking it) is to choose a free software license that respect user's freedom and that forbids redistribution as a privative application.

The usual approach is to release a "copyleft" license such as the GPL and offer alternative licenses for a fee to those who are interested.

So, in practical terms:
- GPL for everyone
- Alternative license possible for a fee on request.

With this approach businesses could use your GPL software if they wanted to, but if they make a modification or a combined work of your software with theirs they will only be able to redistribute it under the GPL (damaging their business model), unless they choose to buy a license from you.

It is not **you** who discriminate who can use your software but rather it's **them** who choose to pay because they don't want to follow the free software path.

Having that in mind, the README could say something like:

> This software is released under GPL. Alternative licenses (usually more attractive for commercial applications) are also available for a fee. Contact <?> for further details.

This is how I believe all major dual licensed software works.

### Further things to consider

Having said that, there are few things you should also be aware of (probably you already are)

- Be careful with the licenses of the software you depend on (so those licenses are compatible with the licenses you want to use for distribution)
- When accepting a copyrightable pull request, ask the contributor of that pull request to grant you permission to grant a license of the software under whatever terms you choose.
- If your software can be used as a service (often used through the network) maybe the [Affero GPL](https://www.gnu.org/licenses/license-list.html.en#AGPL) is able to better protect your interests.

### What happens if you leave things as they are now

-  Non-profit academics (like me) receive from you a GPL licensed copy of your software for nonprofit academic use.
- The rest of the world is not allowed to run your software, use it or redistribute it.
- We all have a license to at least read the code (I have to check this, but it is likely that you granted permission to GitHub to at least display the code and github gives us permission to read it)
- With your wording, you give a single line in the README `for nonprofit academic use` that contradicts a large part of a 10 page long document (the GPL license), and you forbid companies (and hobbyists) to even trying your software. With your current terms, they would need a license from you just to try to run your software, which is probably enough for some of those companies to look for an alternative.

In the end it is all up to the copyright holders of this work. It's their (your?) choice and you can do as you please. My only goal here was to `(a)` describe how common licensing practices are used, `(b)` give some suggestions in good faith on how you could standardize your licensing terms and `(c)` try to contribute to extend free software.

Thanks for your time

**Comment by nephantes** [comment]
Thanks for pointing this out. We want to create an open source and free platform. I will work on this with our UMMS licensing team to make it right.

**Comment by nephantes** [comment]
We keep GPL3 license and removed contradiction in the README. Closing this issue. Thanks for helping us.
